### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by ghost** [Kalmani/npm-bootstrap-stylus#1]
I know this should be in suggestions but i couldnt pull it in there, so, can you upgrade this to bootstrap 3.3.7 and put the fonts in the directory too? please

**Comment by Kalmani** [comment]
Hi, ok I'm on it

**Comment by Kalmani** [comment]
Done. Maybe you can thanks me with a star :p

**Comment by grupoCatolicaInf** [comment]
Sure, where can i do it? I don't use this thing too much

**Comment by ghost** [comment]
Sure, thank you man :)
